!$FG_COLOR = "#FFFFFF"
!$BG_COLOR = "#1287A8"
!$BG_COLOR_ACCENT = "#0d6882"
!$LINE_FG_COLOR = "#333333"
!$EXTERNAL_BG_COLOR = "#0D3D56"
!$NEW_BG_COLOR = "#83B86C"
!$MODIFIED_BG_COLOR = "#C2571A"
!$REMOVED_BG_COLOR = "#AD2A1A"

hide stereotype
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam DefaultFontSize 12
skinparam ArrowColor $LINE_FG_COLOR
skinparam ArrowThickness 0.5
skinparam ArrowFontSize 11
skinparam maxMessageSize 150

skinparam rectangle<<person>> {
    roundCorner 50
}

skinparam rectangle {
    BorderThickness 0
    FontColor $FG_COLOR
    BackgroundColor $BG_COLOR
    BackgroundColor<<new>> $NEW_BG_COLOR
    BackgroundColor<<modified>> $MODIFIED_BG_COLOR
    BackgroundColor<<removed>> $REMOVED_BG_COLOR
    BackgroundColor<<external>> $EXTERNAL_BG_COLOR
}

skinparam database {
    BorderColor $BG_COLOR_ACCENT
    FontColor $FG_COLOR
    BackgroundColor $BG_COLOR
    BackgroundColor<<new>> $NEW_BG_COLOR
    BackgroundColor<<modified>> $MODIFIED_BG_COLOR
    BackgroundColor<<removed>> $REMOVED_BG_COLOR
    BackgroundColor<<external>> $EXTERNAL_BG_COLOR
}

skinparam rectangle<<boundary>> {
    BorderStyle dashed
    BorderThickness 0.5
    BorderColor $LINE_FG_COLOR
    FontColor $LINE_FG_COLOR
    BackgroundColor transparent
}

!procedure ShowLegend()
skinparam Legend {
    BackgroundColor White
    BorderThickness 0
}

!procedure ShowLegend()
legend right
|=                   |= Type         |
|<$BG_COLOR>         | Existing      |
|<$EXTERNAL_BG_COLOR>| External      |
|<$NEW_BG_COLOR>     | New           |
|<$MODIFIED_BG_COLOR>| Modified      |
|<$REMOVED_BG_COLOR> | To be removed |
endlegend
!endprocedure

!procedure Boundary($name, $type)
rectangle "_Spacer()<size:12>$name</size>\n<size:9>[$type]</size>" <<boundary>>
!endprocedure

!procedure Person($label, $desc, $type = "Person")
rectangle _EntityBody($label, $desc, $type) <<person>>
!endprocedure

!procedure System($label, $desc, $type = "Software System")
rectangle _EntityBody($label, $desc, $type)
!endprocedure

!procedure Container($label, $desc)
rectangle _EntityBody($label, $desc, "Container")
!endprocedure

!procedure Container($label, $desc, $tech)
!$type = "Container: " + $tech
rectangle _EntityBody($label, $desc, $type)
!endprocedure

!procedure Component($label, $desc)
rectangle _EntityBody($label, $desc, "Component")
!endprocedure

!procedure Component($label, $desc, $tech)
!$type = "Component: " + $tech
rectangle _EntityBody($label, $desc, $type)
!endprocedure

!procedure Database($label, $desc)
database _EntityBody($label, $desc, "Database")
!endprocedure

!procedure Database($label, $desc, $tech)
!$type = "Database: " + $tech
database _EntityBody($label, $desc, $type)
!endprocedure

!function Tech($tech) return "\n<i>[" + $tech + "]</i>"

!procedure _EntityBody($label, $desc, $type)
"_Spacer()<size:16><b>$label</b></size>\n<size:9>[$type]</size>\n_Spacer()$desc\n"
!endprocedure

!function _Spacer() return "<size:5> </size>\n"