skinparam shadowing false
skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam DefaultFontName Segoe UI
skinparam DefaultFontSize 12
skinparam ArrowColor #111
skinparam ArrowThickness 0.5
skinparam ArrowFontSize 11
skinparam maxMessageSize 150

skinparam rectangle {
    BorderThickness 0
}

!$PERSON_BG_COLOR = "#56B4E9"
!$EXTERNAL_PERSON_BG_COLOR = "#56B4E9"

!$SYSTEM_FG_COLOR = "#FFFFFF"
!$NEW_SYSTEM_FG_COLOR = "#FFFFFF"
!$BOUNDARY_FG_COLOR = "#333333"

!$SYSTEM_BG_COLOR = "#1287A8"
!$EXTERNAL_SYSTEM_BG_COLOR = "#0D3D56"
!$NEW_SYSTEM_BG_COLOR = "#83B86C"
!$MODIFIED_SYSTEM_BG_COLOR = "#C2571A"
!$REMOVED_SYSTEM_BG_COLOR = "#AD2A1A"

skinparam Legend {
  BackgroundColor White
  BorderThickness 0
}

skinparam rectangle {
    BackgroundColor $SYSTEM_BG_COLOR
    FontColor $SYSTEM_FG_COLOR
}

skinparam rectangle<<new>> {
    BackgroundColor $NEW_SYSTEM_BG_COLOR
    FontColor $NEW_SYSTEM_FG_COLOR
}

skinparam rectangle<<modified>> {
    BackgroundColor $MODIFIED_SYSTEM_BG_COLOR
    FontColor $MODIFIED_SYSTEM_FG_COLOR
}

skinparam rectangle<<removed>> {
    BackgroundColor $REMOVED_SYSTEM_BG_COLOR
    FontColor $MODIFIED_SYSTEM_FG_COLOR
}

skinparam rectangle<<external>> {
    BackgroundColor $EXTERNAL_SYSTEM_BG_COLOR
    FontColor $MODIFIED_SYSTEM_FG_COLOR
}

skinparam rectangle<<boundary>> {
    BorderStyle dashed
    BorderThickness 1
    BorderColor $BOUNDARY_FG_COLOR
    FontColor $BOUNDARY_FG_COLOR
    BackgroundColor #FFF
}

hide stereotype
legend right
|=                          |= Type         |
|<$SYSTEM_BG_COLOR>         | Existing      |
|<$EXTERNAL_SYSTEM_BG_COLOR>| External      |
|<$NEW_SYSTEM_BG_COLOR>     | New           |
|<$MODIFIED_SYSTEM_BG_COLOR>| Modified      |
|<$REMOVED_SYSTEM_BG_COLOR> | To be removed |
endlegend

!unquoted function System($alias, $label, $desc, $stereotype = "")
rectangle "_Spacer()<size:16><b>$label</b></size>\n<size:9>[System]</size>\n_Spacer()$desc\n" $stereotype as $alias
!endfunction

!function _Spacer()
!return "<size:5> </size>\n"
!endfunction

!unquoted function Rel($from, $to, $relationship, $tech, $line = "--->")
_Rel($from, $to, "$relationship\n<i>[$tech]</i>", $line)
!endfunction

!unquoted function Rel($from, $to, $relationship = "")
_Rel($from, $to, "$relationship")
!endfunction

!unquoted function _Rel($from, $to, $label = "", $line = "--->")
$from $line $to : "$label"
!endfunction

!unquoted function Boundary($alias, $name, $type)
rectangle "$name\n[$type]" <<boundary>>
!endfunction