@startuml Context Example

skinparam shadowing false
skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam DefaultFontName Segoe UI
skinparam DefaultFontSize 12
skinparam ArrowColor #111
skinparam ArrowThickness 0.5
skinparam ArrowFontSize 11

skinparam rectangle {
    BorderThickness 0
}

!$PERSON_BG_COLOR = "#56B4E9"
!$EXTERNAL_PERSON_BG_COLOR = "#56B4E9"
!$SYSTEM_BG_COLOR = "#56B4E9"
!$SYSTEM_FG_COLOR = "#FFFFFF"
!$EXTERNAL_SYSTEM_BG_COLOR = "#56B4E9"
!$NEW_SYSTEM_BG_COLOR = "#009E73"
!$NEW_SYSTEM_FG_COLOR = "#FFFFFF"
!$MODIFIED_SYSTEM_BG_COLOR = "#E69F00"
!$REMOVED_SYSTEM_BG_COLOR = "#D55E00"

skinparam Legend {
  BackgroundColor White
  BorderThickness 0
}

skinparam rectangle {
    BackgroundColor $SYSTEM_BG_COLOR
    FontColor $SYSTEM_FG_COLOR
}

skinparam rectangle<<new>> {
    BackgroundColor $NEW_SYSTEM_BG_COLOR
    FontColor $NEW_SYSTEM_FG_COLOR
}

skinparam rectangle<<modified>> {
    BackgroundColor $MODIFIED_SYSTEM_BG_COLOR
    FontColor $MODIFIED_SYSTEM_FG_COLOR
}

skinparam rectangle<<removed>> {
    BackgroundColor $REMOVED_SYSTEM_BG_COLOR
    FontColor $MODIFIED_SYSTEM_FG_COLOR
}

hide stereotype
legend right
|=                         |= Type         |
|<$SYSTEM_BG_COLOR>         | Existing      |
|<$NEW_SYSTEM_BG_COLOR>     | New           |
|<$MODIFIED_SYSTEM_BG_COLOR>| Modified      |
|<$REMOVED_SYSTEM_BG_COLOR> | To be removed |
endlegend

!unquoted function System($alias, $label, $desc, $stereotype = "")
rectangle "_Spacer()<size:14><b>$label</b></size>\n<size:9>[System]</size>\n_Spacer()$desc\n" <<system>> $stereotype as $alias
!endfunction

!function _Spacer()
!return "<size:5> </size>\n"
!endfunction

!unquoted function Rel($from, $to, $desc = "")
$from ..> $to : "$desc"
!endfunction

' Sample diagram

System(system1, "System 1", "Does something important")
System(system2, "System 2", "Does something else important", <<new>>)
System(system3, "System 3", "Not sure what this does", <<modified>>) 
System(system4, "System 4", "Something else altogether", <<removed>>) 

Rel(system1, system2, "Does something")
Rel(system1, system3)
Rel(system1, system4)

@enduml